### ISSUE TITLE
`QUESTION`

### ISSUE THREAD

**Issue by ORCA666** [stephenbradshaw/vulnserver#3]
Hello man, that is a nice project, I'm kinda new to exploit development / Windows exploiting so do you know such projects like this (vulnerable & built to be hacked) I'm not talking about hackthebox or something like that, I need like a software that can be downloaded on my vm and be executed, if it is a cve (real world example) that would be crazy ...
Thanks for uploading this, hope you reply 🙂

**Comment by stephenbradshaw** [comment]
Im not aware of any other commonly available Windows app that focuses on memory corruption style exploitation, which maybe explains why this bit of software I wrote >10 years ago is still actually popular, despite the fact that exploit mitigation technologies in the OS have moved on a lot since then. The only other Windows app Im aware of that is built to be exploited is DVTA https://github.com/srini0x00/dvta, although the focus there is slightly different. I don't really keep track of this however, so its probably worth doing your own searching...

**Comment by ORCA666** [comment]
oh, okay, do you know something else to exercise exploit development  ? like a website or something, a while ago i found a website  that have multiple files named as CVE's and you can actually download it and run it and try to exploit it, however forgot to bookmark it and i lost it, anyways do you know any same ideas website

**Comment by stephenbradshaw** [comment]
Google would be able to give you a better list of resources than me, but this guy is well regarded when it comes to this type of thing on Windows:
https://www.corelan.be/
